import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Header from '@/components/Header'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: 'News Application',
  description: 'Generated by free News api',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main >{children}</main></body>
    </html>
  )
}
